title:  Setup Canon Printer on MAC 
description: Canon printer is supportable on each and every device. Visit ij.start.canon and connect the canon printer with your mac device. Install and setup canon ij setup using simple procedure. 
theme: jekyll-theme-cayman
